AllCops:
    NewCops: enable

Layout/IndentationStyle:
  EnforcedStyle: tabs
  IndentationWidth: 1

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false