AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Enabled: false
# Layout/LineLength:
#   Enabled: true
#   Max: 80
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/IndentationStyle:
  EnforcedStyle: tabs
Layout/IndentationWidth:
  Width: 1
