# frozen_string_literal: true

ruby '3.3.3'
source 'https://rubygems.org'

gem 'debug', require: false
gem 'rubocop', '~> 1.69', require: false

gem 'sorbet', group: :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, group: %i[development test]

gem 'gruff'

gem 'rbs'

gem 'ruby-sfst'

gem 'gdbm'

gem 'coderay'
gem 'colorize'
gem 'readline'
gem 'reline'
