# frozen_string_literal: true

ruby '3.3.3'
source 'https://rubygems.org'

gem 'debug', require: false
gem 'gdbm'
gem 'rubocop', '~> 1.60'

gem 'sorbet', group: :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, group: %i[development test]

gem 'gruff'