[package]
name = "evaluations"
version = "0.1.0"
edition = "2021"

[dependencies]
# fst = { version = "0.4", features = ["levenshtein"] }
fst = { version = "0.4" }
levenshtein_automata = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
num-bigint = "0.4"
